- name: check if OS is compatible
  fail:
    msg: "Failed: the OS which you tried is incompatible"
  when: not (ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7") and
        not (ansible_distribution == 'RedHat' and ansible_distribution_major_version == "7")
