---
- { include: includes/hosts.yml, when: "groups['master']|length > 0" }
- { include: includes/rabbitmq.yml, when: "groups['rabbitmq']|length > 0" }
- { include: includes/cluster.yml, when: "groups['slaves']|length > 0" }
- { include: includes/haproxy.yml, when: "groups['haproxy']|length > 0" }