- name: open haproxy ports on firewalld
  firewalld:
    port: "{{ item['value'] }}/tcp"
    permanent: true
    state: enabled
  ignore_errors: yes
  with_dict: "{{ hap['ports'] }}"

- name: restart firewalld
  systemd:
    name: firewalld.service
    state: restarted